### ISSUE TITLE
The input element's type ('number') does not support selection. (l149)

### ISSUE THREAD

**Issue by Mouvedia** [AlphaGit/ng-pattern-restrict#12]
cf Mottie/Keyboard#241

chrome 41.0.2247.0 canary

**Comment by AlphaGit** [comment]
Hi! I made a few improvements in that regards as well as other refactorings and having more browsers into the tests.

I still need to test some stuff manually, as I don't know how I'd automate the drag-and-hold method for selection (left to right or right to left) that was giving me issues before, but hopefully we've had an improvement.

If you're curious, you can take a look at it at this branch: https://github.com/AlphaGit/ng-pattern-restrict/compare/fixing-chrome-selection-support.
