### ISSUE TITLE
restriction is not working [opera]

### ISSUE THREAD

**Issue by Mouvedia** [AlphaGit/ng-pattern-restrict#13]
Using `pattern="\d*" ng-pattern-restrict type="number"` I can type letters in my input.

opera version 12.16 rev 1860
angular 1.3.5

**Comment by Mouvedia** [comment]
It was me indeed ^^

line 105 is too restrictive. It might require some tests with other types like tel for example.
Sorry for the delay, it's working fine on my side you can merge it and close this issue.

Concerning #12, seeing errors in my console bothered me. The fact that the caret doesn't keep its position is not a great loss. If I could I would have labeled 12 as a minor annoyance.

**Comment by AlphaGit** [comment]
Thanks! I've merged #14 and that should solve this problem! Thanks for coming back to this.

Closing this ticket.
