### ISSUE TITLE
Unhandled exception when is used with input type="email"

### ISSUE THREAD

**Issue by sebaplaza** [AlphaGit/ng-pattern-restrict#18]
Uncaught InvalidStateError: 

Failed to read the 'selectionStart' property from 'HTMLInputElement': The input element's type ('email') does not support selection.

ng-pattern-restrict.js:149 
getCaretPositionng-pattern-restrict.js:133 
updateCurrentValueng-pattern-restrict.js:111 
genericEventHandlerjquery.js:4430 
jQuery.event.dispatchjquery.js:4116

**Comment by AlphaGit** [comment]
@sebaplaza Thanks! Did you find this in any particular browser? (I think I can start working on it anyway.)

**Comment by AlphaGit** [comment]
Note: this may be related with #12. There's a pending branch there on which I need to perform some further testing.
