### ISSUE TITLE
The keyboard opens in the browser Safari (IOS 8) when pressing in any place on the page

### ISSUE THREAD

**Issue by yukozlovskiy** [AlphaGit/ng-pattern-restrict#21]
Step to reproduce:
1. Open page with input when you use ng-pattern-restrict on your iPhone
2. Tap in any place on the page
3. Keyboard opens and form filed becomes focused
4. When you refresh the page, you can reproduce this bug again

The problem in function detectSetCaretPositionMethods().  When I have commented this function everything works fine.

**Comment by AlphaGit** [comment]
Fixed on cae78314fe1d6529166a472c46bf101153e6a42c.
