### ISSUE TITLE
Problem with 'backspace' and 'delete' key

### ISSUE THREAD

**Issue by nhung0631** [AlphaGit/ng-pattern-restrict#25]
I've run this app with 2 cases as below:
1. input valid character -> press ' Backspace' on keyboard => the first character can't delete.
2. input valid character -> select all text -> press 'Backspace' or 'Delete' on keyboard => text can't delete
Can you help me solve this problem? Thanks.

**Comment by AlphaGit** [comment]
Does your regex allow for the incomplete expression?

Check this note from the Readme.md file:

> - (#15) Make sure to use "progressive" regular expressions. The expressions are validated against the full regular expression. This means that if your regex is `\d\d`, and your textbox is empty, a user will never be able to type anything because the first keypress will not validate and will be reverted. Following the example, the proper regular expression should be `\d{0,2}`.
> - Your regex must validate against empty strings if you want users to be able to remove the value from the textbox.

**Comment by nhung0631** [comment]
Maybe my expression is not good. If expression is ^[0-9]*$, it will working. But if expression is ^[0-9]+$, it will be problem as on

**Comment by AlphaGit** [comment]
Exactly: the expression with `+` does not validate against an empty string, so the input will be considered not valid and the directive will prevent that change.
