### ISSUE TITLE
How to pass pattern dynamically into directive

### ISSUE THREAD

**Issue by itsmefirealex** [AlphaGit/ng-pattern-restrict#27]
assume that i have text box. dynamically i want to pass the pattern. I tried following thing but not working.

Html:
<inpyt type="text" ng-pattern-restrict="setPattern()" />

Script:
$scope.setPattern = function() {
  var pattern = /^([0-9]+ ?)*$/;
  return pattern;
};

but in the above code setPattern() function is not getting called. Is there any way to send patterns dynamically.

Thanks in advance..

**Comment by mathiasdose** [comment]
I am also wondering about this.

**Comment by AlphaGit** [comment]
Hi! Yes, I actually do this to automate tests.

In your controller:

```javascript
$scope.myPattern = /whatever/;
```

In your view:

```html
<input type="text" ng-pattern="{{myPattern}}" />
```` 

The pattern will change if you change the $scope variable as well.

**Comment by itsmefirealex** [comment]
I tried as below but no luck

In my View 

input type="text" ng-pattern-restrict="{{pattern}}" 

In my controller:

$scope.pattern = /^([0-9]+ ?)*$/;

**Comment by AlphaGit** [comment]
Oops, my bad. You may need a string representation of your pattern.

In your controller:

```javascript
$scope.pattern = "^([0-9]+ ?)*$";
```

**Comment by itsmefirealex** [comment]
It works well.

Thanks a log AlphaGit :+1:

**Comment by AlphaGit** [comment]
I'm glad I was able to help! Have a great weekend. :)

**Comment by mathiasdose** [comment]
Yep works great, thanks for fast answer!
