### ISSUE TITLE
Compatibility issue between ui-grid, ng-pattern-restrict and IE11

### ISSUE THREAD

**Issue by mathiasdose** [AlphaGit/ng-pattern-restrict#28]
I've got a compatibility issue between ui-grid (https://github.com/angular-ui/ui-grid), ng-pattern-restrict and IE11. 

The problem is that when trying to edit a cell, which when in edit mode is an input element with ng-pattern-restrict attached to it (using custom template), the code below will cause the cell to immediately close again.
```javascript
notThrows(function () { input.setSelectionRange(0, 0); })
```

I've made two plunkers to make it easier to grasp the problem, here is a plunker with the problem: http://plnkr.co/edit/ZUxXAMMqRpQ1ksTUcI2u?p=preview

If you target a cell on the last row and the row isn't completely visible as illustrated on the picture below, and then try to write any number (my demo regexp only allows numbers), you'll see that the cell stutters and don't enter edit mode. If you want to see how it should look like just edit any other cell on any other row. 
![screen shot 2015-09-03 at 12 35 44](https://cloud.githubusercontent.com/assets/2345409/9656713/c2b502c6-523a-11e5-8799-9507f5492d3a.jpg)

I have identified the problem to the code snippet pasted above, here is a plunker using a typeOf check instead, which seems to solve the problem at least for this case: http://plnkr.co/edit/4BeVS7wcTST5Swpx7yQl?p=preview

I saw that in #24 you touch this part of the code, and that change would maybe fix my issue. How is that pull request coming along?

**Comment by AlphaGit** [comment]
Hi! First of all, thank you very much for this great detailed bug report. I really appreciate the effort you put into it.

On the code change, it's been pretty much stuck on webdrivers giving me hell on non-text inputs, which really impedes my ability to check browser compatibility. I've been waiting on some colleague's input on Sikuli, which may help in overcoming that, but CI integration is going to be a whole other subject.

I think the best option might be to drop some browsers off the compatibility matrix, setup a bunch of VMs (Linux, Windows, Mac) with a bunch of browsers (FF, IE, Chrome, Safari at the very least) and test it out manually. I'll see if I can setup something over the weekend and at least get these bugs out of the way.

Any ideas would be appreciated.

**Comment by mathiasdose** [comment]
Thanks for quick reply!

I've seen https://saucelabs.com/home been used for CI testing cross browsers, it's free for open source projects also.

**Comment by AlphaGit** [comment]
Yes, that exactly what I've been experimenting with. This is one of the tests, as an example, with the new code: https://saucelabs.com/beta/tests/798a31ea6064498db7f7c418cecda0d1

**Comment by AlphaGit** [comment]
@mathiasdose Hi! The problem was effectively fixed with the changed you mentioned. Those had been already incorporated in the master branch, on the commit cae78314fe1d6529166a472c46bf101153e6a42c.

Thanks for the Plunkr, it made it really easy to verify!

**Comment by mathiasdose** [comment]
@AlphaGit Awesome, thanks for the help!

**Comment by mathiasdose** [comment]
@AlphaGit How long can I expect before I see the update on bower?

**Comment by AlphaGit** [comment]
@mathiasdose I was expecting to wrap up some other tasks before releasing the new version. It may take a while (a few days... weeks?). [These are the tasks I wanted to finish](https://github.com/AlphaGit/ng-pattern-restrict/milestones/v0.2.0).

If you need it right now, I'd suggest you point bower to the particular hash of the latest commit right now, or to master directly if you want to get the latest whenever it is updated.

**Comment by mathiasdose** [comment]
@AlphaGit Okey I'll point it to the latest commit.

**Comment by AlphaGit** [comment]
@mathiasdose Sorry to bother you again, but I just released 0.2.0 with the latest changes and I thought you'd like to know. ;)
