### ISSUE TITLE
Pressing invalid key adds ng-invalid class

### ISSUE THREAD

**Issue by Yuripetusko** [AlphaGit/ng-pattern-restrict#31]
When pressing invalid key on the keyboard it does add ng-invalid class to the input, pressing invalid key again removes ng-invalid class

```
<input type="text" placeholder="First Name" ng-model="vm.profile.first_name" ng-pattern="/^$|[a-zA-Z-\-\ ']+$/" ng-pattern-restrict />
```

**Comment by AlphaGit** [comment]
Thank you very much!

I think this may be related to #17, but I haven't done investigation on any of these. I'll take a look at these later.

**Comment by AlphaGit** [comment]
I was not able to reproduce this problem with Angular 1.4.7. I tested manually with Chrome 45 and Firefox 40. Then I ran an automatic test and all browsers seemed to not have this problem.

Here's the test I built to check this:

```html
<form name="testForm">
  <label for="textbox">Text 1:</label>
  <input type="text" id="textbox1" name="textbox1" ng-pattern="/^[abc]*$/" ng-pattern-restrict ng-model="modelValue" />

  <p>textbox.valid: <span id="ngValid">{{testForm.textbox1.$valid}}</span></p>
</form>
```

```javascript
it('should leave input always in a valid state', function() {
  //valid input
  page.setText('abc');
  expect(page.getValidStatusPromise()).toBe("true"); // gets the contets of #ngValid

  //invalid input
  page.setText('def');
  expect(page.getValidStatusPromise()).toBe("true"); // gets the contets of #ngValid
});
```

While on the test I checked for the $valid attribute of the input, I was not able to see at any point that the ng-invalid was added to the input or to the form at all.

Do you have any other detail I could use to reproduce the problem?

**Comment by AlphaGit** [comment]
PS: If you want to work off of the test I built, I had started it in the [fix-validation-issues branch](https://github.com/AlphaGit/ng-pattern-restrict/tree/fixing-validation-issues).

**Comment by AlphaGit** [comment]
Hi! I haven't heard back from you and I haven't yet found a way to reproduce this problem.

I'll close this ticket for now, and if you or somebody else comes up with a way of reproducing it, feel free to let me know and I'll reopen it or we can just start another discussion.

In the meantime I'll add these new tests to the master branch so that they're ready for everyone to start the troubleshooting.
