### ISSUE TITLE
Number range

### ISSUE THREAD

**Issue by shlomogoldstein** [AlphaGit/ng-pattern-restrict#37]
Does your directive support number ranges? Like preventing a number out of range of 1 to 1000 ?
I have used your directive in another project. It worked, thank you. I can hardly find any other project for restricting input for angular. Do you know any other??

**Comment by AlphaGit** [comment]
Hi! I'm really glad you're liking the project and finding it useful.

It doesn't support number ranges directly, but you should be able to support it with regexes.

ˋ^\d{,4}$ˋ would be a simple way of accepting up to 4 digits. If you want to make sure that it doesn't have leading zeroes, you could do something like ˋ^0|\d{,4}$ˋ. However, if you want specific ranges or decimals or custom ranges, your regex may be a little bit more complicated.

**Comment by AlphaGit** [comment]
@shlomogoldstein Have you had to chance to try any of the approaches? Let me know if they helped you out.

**Comment by shlomogoldstein** [comment]
Thank you for the response. We are using another approach for validating so I do not use ranges anymore. But the regex validation works

**Comment by AlphaGit** [comment]
Sounds good -- thanks!
