### ISSUE TITLE
Allow npm install

### ISSUE THREAD

**Issue by battmanz** [AlphaGit/ng-pattern-restrict#40]
Could you make it possible to install this via npm? I'm using browserify and all of my other packages (including angular) can be installed via npm.

**Comment by AlphaGit** [comment]
Hi! Sure, I'll work on that.

While I get that done, you should be able to point the npm dependency to the repository. You may even point to a particular commit or tag if you're worried about the incoming changes.

```js
"dependencies": {
  "ng-pattern-restrict": "https://github.com/AlphaGit/ng-pattern-restrict.git#v0.2.0"
}
```` 

However, I'll still work to get it today or tomorrow into the npm registry. Thanks!

**Comment by battmanz** [comment]
Thanks for getting back to me so fast! Unfortunately is won't work to install directly from github, because there is no version specified in the `package.json` file. I get the following error
    npm ERR! No version provided in package.json

**Comment by AlphaGit** [comment]
@battmanz Got it!

I just published to the npm registry, you should be able to get it with 

```console
npm install ng-pattern-restrict
```

The version right now is 0.2.1.

Thanks!

**Comment by battmanz** [comment]
Thank you!
