### ISSUE TITLE
v0.2.2 is not published in npm

### ISSUE THREAD

**Issue by jcperez-ch** [AlphaGit/ng-pattern-restrict#46]
Currently I am trying to use this package via `npm` like

```
npm install --save ng-pattern-restrict
```

The problem is that the latest published version in npm is v0.2.1 which doesn't include the main file commit:

https://github.com/AlphaGit/ng-pattern-restrict/commit/291c3bb51a33024cf4742f5d887c62b75eaf86c5

This may cause problems with some module bundlers like rollup or webpack.

**Comment by AlphaGit** [comment]
Hi! You're probably referring to version 0.2.1. You're right, I probably missed publishing to the npm repository. I will do so very soon. 

In the meantime, feel free to use the URL to this repo with the tag for the version in the npm dependency.

**Comment by AlphaGit** [comment]
I have now published 0.2.2 to npm. Thanks!
