### ISSUE TITLE
Angular 1.5 and 1.6 support

### ISSUE THREAD

**Issue by sinner** [AlphaGit/ng-pattern-restrict#47]
Now we are migrating all our code to the new features of Angular 1.5 and 1.6 and this bower.json definition is giving us a lot of problems...

**Comment by AlphaGit** [comment]
Hi @sinner, thanks for the heads up. I'll reserve some time to test it out in Angular 1.5 and 1.6 and update the tests. If everything goes right, we can just upgrade what we support. Otherwise, it may take a little longer to ensure that everything works right.

(BTW, I love your username. :) )

**Comment by AlphaGit** [comment]
Hi! I just noticed that the current bower definition is `"angular": "^1.2.27 ^1.3.0"`, which means that 1.5 and 1.6 should be allowed.

While this is a mistake (I didn't intend to allow them freely), it should not be giving you any problems. What problems are you exactly having?

**Comment by miclill** [comment]
Works for me with angular 1.6 as far as I can tell.

**Comment by AlphaGit** [comment]
Hey @sinner, would you mind to let me know what problems are you having exactly?
