### ISSUE TITLE
Add mention of adding 'ngPatternRestrict' to app modules in README.md

### ISSUE THREAD

**Issue by aplocher** [AlphaGit/ng-pattern-restrict#51]
README.md misses a generally well-known (but crucial) step between installation and usage.  

Currently installation says:

> Installation
> bower install ng-pattern-restrict
>   \# or
> npm install ng-pattern-restrict
> Alternatively, copy the ng-pattern-restrict.js (or the minified version ng-pattern-restrict.min.js) into your project, load it into the browser and use it away.

Recommended update (changed last sentence and added a couple new lines with example):

> Installation
> bower install ng-pattern-restrict
>   \# or
> npm install ng-pattern-restrict
> 
> Alternatively, copy the ng-pattern-restrict.js (or the minified version ng-pattern-restrict.min.js) into your project and reference it in your index.html.
> 
> Finally, add a module reference (typically in app.js) to ngPatternRestrict.  e.g.:
> 
> angular.module('yourApp', [
>   ... other modules ...,
>   'ngPatternRestrict']);

**Comment by AlphaGit** [comment]
👍 Sounds like a good idea. I'll be updating it pretty soon.

**Comment by aplocher** [comment]
Thank you!  I was brain-dead the other night working on this stuff and stared at my code for about 20 mins before realizing I forgot that! :-)

**Comment by AlphaGit** [comment]
Haha, not a problem. Thanks for turning your bad experience into something useful for everyone. That's the open source spirit at its best! 👍
