### ISSUE TITLE
Floating number is not working

### ISSUE THREAD

**Issue by sadashivm** [AlphaGit/ng-pattern-restrict#55]
i need floating number like
10
12.34
0.45

and written code like

`  <form name="userForm" autocomplete="off" novalidate >
            <div class="row" style="margin-top: 4em">
                <div class="col-md-6">
                   <div class="form-group">
                        <label>Allow Floating Numbers <span >[ Ex.12.35 ]</span></label>
                        <input type="text" class="form-control" name="txt7" ng-model="user.txt7" 
                                ng-pattern="/^(?:[1-9]\d*|0)?(?:\.\d+)?$/"  ng-pattern-restrict required  />                          
                    </div>                    
                    <button type="button" class="btn btn-primary" ng-disabled="userForm.$invalid">Submit</button>                    
                </div>
            </div>
        </form>
`

the above regular expression is not working can u help me.

**Comment by AlphaGit** [comment]
Hi! Sure, this is your current pattern: `/^(?:[1-9]\d*|0)?(?:\.\d+)?$/`

Notice that if you were to enter a decimal point, you are forced to enter a digit for it to pass the regular expression. You need to make the digits optional so that you can type the decimal point first, and then numbers. So change the last `+` by a `*` and you should be good.

**Comment by sadashivm** [comment]
Thank you for your response.

My requirement is not matching to this pattern. i mean the above pattern is taking `.(dot)` as a first letter , it should be wrong. my requirement as below

The valid inputs are
    **10
    10.25
    0.34
    2.5
    0.2**

The Invalid inputs are
    **10.
    .25**

Ex.  If i enter number like **`10.` or `.25`** button should be disable.

Can you tell me exact pattern for above requirement. you can change whole pattern no problem.

for reference i have created example in plunker please check it.
https://plnkr.co/edit/bNS3h1peOQqx5sAPN1ux?p=preview

**Comment by AlphaGit** [comment]
> Ex. If i enter number like 10. or .25 button should be disable.

That's not really what this module does. This module will prevent invalid input, so you need to allow for partial input. See the [documentation notes](https://github.com/AlphaGit/ng-pattern-restrict#notes). Basically, if you don't allow `10.`, the user will never get to type it so they will never be able to enter `10.1`.

Disabling / enabling a button can be done by using form validations, as you correctly used in your plunkr.

What you may do is pass different patterns to ng-pattern-restrict and to ng-pattern. The pattern for ng-pattern-restrict should allow partial input (as I just mentioned), and the pattern for ng-pattern would not allow it, validating against wrong formats.

Check out this plunkr, modified from yours: https://plnkr.co/edit/uTZxep5qifLsPdcuE9O0?p=preview

Here are the relevant bits:

```html
<input type="text"
    ng-pattern="/^\d+(\.\d+)?$/"
    ng-pattern-restrict="^([1-9]\d*|0)?(\.\d*)?$" />
```

**Comment by sadashivm** [comment]
thanks dear 
its working fine.
