### ISSUE TITLE
It doesn't allow copy and paste feature

### ISSUE THREAD

**Issue by sinner** [AlphaGit/ng-pattern-restrict#57]
It doesn't allow copy and paste feature

**Comment by AlphaGit** [comment]
Hi @sinner, thanks for the submission. Would you mind to provide more information on how to reproduce? As far as I'm aware, copy and paste are supported.

**Comment by AlphaGit** [comment]
Hi @sinner -- I haven't heard back from you so I'll be closing this issue. If you needed anything else, feel free to ask!
