### ISSUE TITLE
When using ng-pattern-restrict with md-maxlength in textarea the character count for pasted invalid text is incorrect

### ISSUE THREAD

**Issue by apedneka1** [AlphaGit/ng-pattern-restrict#58]
Hi @AlphaGit ,
I observed that when you paste invalid text in a text area with max-length set using the md-maxlength directive, the character count is updated to the length of the invalid text even though the value of the text area is not updated. As result you get an empty text area with non-zero character count value.

Similarly, let's say you have some valid text in the text area. If you select the entire text and paste invalid text, similar to the first scenario, the character count will update to the length of the pasted invalid text but the text area retains the previous valid value resulting into a mismatch of the character count value and the actual length of text in the text area.

You can try both these scenario in my [codepen](https://codepen.io/greuniv/pen/KJwpbL)
Scenario 1: Paste text "!@#$%&" in the textarea. You will get an empty text area with character count 6/10.

Scenario 2: Enter text "abc" in the text area. Now select the entire text and paste "!@#$%&". The textarea will display text "abc" but the character count will be 6/10

Thanks.

**Comment by AlphaGit** [comment]
Hi @apedneka1 -- thank you very much for the detailed submission. I was able to reproduce the issue with your codepen. Furthermore, I found another case:

Scenario 3: Type "ab". The count will correctly increase to 2. Type "!". The text will remain as "ab" (ok), but the count will increase to 3 (not ok).

This project is not under maintenance anymore but I'll take a look anyway and see if I can figure out a quick solution or workaround. Thank you!

**Comment by apedneka1** [comment]
Thank you @AlphaGit.

Thank you,
Ashish Pednekar
Software Engineer
Paychex, Inc.

**Comment by AlphaGit** [comment]
Hi @apedneka1!

I cannot reproduce this issue anymore in the latest version of the code. I have a gut feeling that this was solved in #44, released in 0.2.2.

I have verified that 0.2.3 is available in npm and bower.

**Comment by AlphaGit** [comment]
@apedneka1 I have published a new [codepen](https://codepen.io/anon/pen/BMNmwv) you can use to verify the behavior in the latest version.

**Comment by apedneka1** [comment]
Thank you @AlphaGit. I latest version seems to have fixed that bug.
