### ISSUE TITLE
Exception thrown in firefox "Uncaught DOMException: An attempt was made to use an object that is not, or is no longer, usable"

### ISSUE THREAD

**Issue by yftachman** [AlphaGit/ng-pattern-restrict#60]
Have an input with a restriction like "[0-9]*", when I enter a character that is not a number an exception is thrown "Uncaught DOMException: An attempt was made to use an object that is not, or is no longer, usable"

this happens at 
`function setCaretPositionWithSetSelectionRange(position) {
            iElement[0].setSelectionRange(position, position);
          }`

but the actual problem is that the position that is sent is "null" but the check beforehand is only checking for undefined and not for null

`          function revertToPreviousValue() {
            iElement.val(oldValue);

            if (!angular.isUndefined(carentPosition)) {
              setCaretPosition(caretPosition);
            }
          }`

**Comment by yftachman** [comment]
pull request for a fix: https://github.com/AlphaGit/ng-pattern-restrict/pull/61

**Comment by AlphaGit** [comment]
Solved by merged PR. Thank you!
